mode: rule
loglevel: silent
mixed-port: 7899
allow-lan: false
clash-for-tsg:
  dns-proxy:
    enable: true
    copy-rules: mode-all
    custom-rules: 
      - DOMAIN-SUFFIX,tikvpn.in,DIRECT
      - DOMAIN-SUFFIX,tikvpn.net,DIRECT
      - DOMAIN-SUFFIX,branchcn.com,DIRECT
      - DOMAIN-SUFFIX,tikvpn.com,DIRECT
      - DOMAIN-SUFFIX,tikvpn.app,DIRECT
      - DOMAIN-SUFFIX,b.tikvpn.in,DIRECT
      - DOMAIN-SUFFIX,pushnotificationws.com,DIRECT
      - DOMAIN-SUFFIX,b.tikvpn.net,DIRECT
      - DOMAIN-SUFFIX,b.tikvpn.com,DIRECT
      - DOMAIN-SUFFIX,b.tikvpn.app,DIRECT
      - DOMAIN-SUFFIX,allapp.link,DIRECT
      - DOMAIN-SUFFIX,dlynankz.biz,DIRECT
      - DOMAIN-SUFFIX,38.54.36.1922,DIRECT
      - MATCH,PROXY
  direct-ip-rule:
    enable: true
    ip-list:
      - 47.246.48.206
      - 139.59.173.173
      - 103.253.73.115
      - 188.114.96.0
      - 188.114.97.0
      - 188.166.253.150
      - 143.244.138.11
      - 188.246.206.109

dns:
  enable: true
  ipv6: false
  use-hosts: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  nameserver-policy:
    '+.tikvpn.com': 'https://1.1.1.1/dns-query'
    '+.tikvpn.in': 'https://1.1.1.1/dns-query'
    '+.tikvpn.net': 'https://1.1.1.1/dns-query'
    '+.tikvpn.app': 'https://1.1.1.1/dns-query'
  default-nameserver:
    - udp://1.1.1.1:53
    - udp://8.8.8.8:53
    - tcp://1.1.1.1:53
    - tcp://8.8.8.8:53
    - tls://1.1.1.1:853
  nameserver:
    - udp://1.1.1.1:53
    - udp://8.8.8.8:53
    - tcp://1.1.1.1:53
    - tcp://8.8.8.8:53
    - tls://1.1.1.1:853
  fallback:
proxies: 
  - name: "N0:5.188.168.238"
    type: trojan
    server: 5.188.168.238
    port: 443
    password: bf0XBBj6W1R9298w
    network: ws
    sni: 
    skip-cert-verify: true
    udp: true
    ws-opts: 
      path: /rainbow/mika
      
  - name: "N1:82.208.20.248"
    type: trojan
    server: 82.208.20.248
    port: 443
    password: 15rQ03UWMj0cNB2L
    network: ws
    sni: 
    skip-cert-verify: true
    udp: true
    ws-opts: 
      path: /rainbow/mika
      
  - name: "N2:82.208.20.224"
    type: trojan
    server: 82.208.20.224
    port: 443
    password: kB54cHQILF3Y8vKv
    network: ws
    sni: 
    skip-cert-verify: true
    udp: true
    ws-opts: 
      path: /rainbow/mika
      
proxy-groups:
  - name: "ProxyGroup"
    type: url-test
    proxies:
      - N0:5.188.168.238
      - N1:82.208.20.248
      - N2:82.208.20.224
    url: 'http://www.gstatic.com/generate_204'
    tolerance: 150
    interval: 300
    fail-test: true
rules: 
  # server 
  - DOMAIN-SUFFIX,tikvpn.in,DIRECT
  - DOMAIN-SUFFIX,tikvpn.net,DIRECT
  - DOMAIN-SUFFIX,branchcn.com,DIRECT
  - DOMAIN-SUFFIX,tikvpn.com,DIRECT
  - DOMAIN-SUFFIX,tikvpn.app,DIRECT
  - DOMAIN-SUFFIX,b.tikvpn.in,DIRECT
  - DOMAIN-SUFFIX,pushnotificationws.com,DIRECT
  - DOMAIN-SUFFIX,b.tikvpn.net,DIRECT
  - DOMAIN-SUFFIX,b.tikvpn.com,DIRECT
  - DOMAIN-SUFFIX,b.tikvpn.app,DIRECT
  - DOMAIN-SUFFIX,allapp.link,DIRECT
  - DOMAIN-SUFFIX,dlynankz.biz,DIRECT
  - DOMAIN-SUFFIX,38.54.36.1922,DIRECT
  - DST-PORT,853,ProxyGroup
  - DST-PORT,53,ProxyGroup
  - DOMAIN-SUFFIX,doh.pub,ProxyGroup
  - DOMAIN-SUFFIX,dns.rubyfish,ProxyGroup
  - DOMAIN,223.5.5.5,ProxyGroup
  - DOMAIN,223.5.5.5,ProxyGroup
  - DOMAIN-SUFFIX,cloudflare-dns,ProxyGroup
  - DOMAIN-SUFFIX,dns.rubyfish,ProxyGroup
  - IP-CIDR,8.8.8.8/32,ProxyGroup
  - IP-CIDR,8.8.4.4/32,ProxyGroup
  - IP-CIDR,1.1.1.1/32,ProxyGroup
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,198.18.0.0/16,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - IP-CIDR6,fd00::/8,DIRECT,no-resolve
  - DOMAIN-KEYWORD,announce,DIRECT
  - DOMAIN-KEYWORD,torrent,DIRECT
  - DOMAIN-KEYWORD,tracker,DIRECT
  - DOMAIN-SUFFIX,smpt,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,ProxyGroup